# Generated by Django 3.1.2 on 2020-11-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couple',
            name='date_of_event',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='person2_first_name',
        ),
        migrations.RemoveField(
            model_name='couple',
            name='person2_last_name',
        ),
    ]
