# Generated by Django 3.1.3 on 2020-11-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('couples', '0002_auto_20201111_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Couple',
        ),
    ]
