# Generated by Django 3.1.3 on 2020-11-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201110_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='person2_first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person2_last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name_of_event',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
