# Generated by Django 3.1.2 on 2020-11-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201111_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='person2_first_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='wedding_category',
            field=models.CharField(blank=True, choices=[('couple', 'Couple'), ('vendor', 'Vendor'), ('wedding_planner', 'Wedding Planner')], default='couple', max_length=16, null=True),
        ),
    ]
